spring:
  application:
    name: service-provider
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  # 配置区域感知增加的配置
  instance:
    metadata-map:
      zone: gcp
    zone: gcp
    
# 日志配置
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG