spring:
  application:
    name: eureka-server

server:
  port: 8762

eureka:
  instance:
    metadata-map:
      zone: aws
    zone: aws
  client:
    register-with-eureka: true
    fetch-registry: true
    preferSameZoneEureka: true
    availabilityZones:
      default: aws,gcp
    serviceUrl:
      aws: http://localhost:8762/eureka/
      gcp: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false 