spring:
  application:
    name: service-consumer

server:
  port: 8002
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    metadata-map:
      zone: gcp
    zone: gcp

# Ribbon配置
service-provider:  # 服务提供者的应用名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule  # 使用区域感知策略

# Feign配置
feign:
  client:
    config:
      service-provider:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.netflix.loadbalancer: DEBUG
    org.springframework.cloud.netflix.ribbon: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG 