spring:
  application:
    name: service-consumer
  cloud:
    loadbalancer:
      zone: aws
      configurations: zone-preference
      
server:
  port: 8002
        
eureka:
  instance:
    metadata-map:
      zone: aws
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-same-zone-eureka: true

# 简单的Feign配置
feign:
  client:
    config:
      service-provider:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.netflix.loadbalancer: DEBUG
    org.springframework.cloud.netflix.ribbon: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG 