spring:
  application:
    name: service-provider
    
server:
  port: 8003
  
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: https://eureka.bitmartgcp-test.com/eureka/
    prefer-same-zone-eureka: true
    region: region1
    availability-zones:
      region1: aws,gcp
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: aws
    zone: aws
    # 更快的心跳检测
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    
# 日志配置
logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix.eureka: INFO 